version: "3.8"

services:
  db:
	image: mysql:5.7
	container_name: mysql-db
	restart: always
	environment:
  	MYSQL_ROOT_PASSWORD: rootpass
  	MYSQL_DATABASE: webapp
  	MYSQL_USER: webuser
  	MYSQL_PASSWORD: webpass
	volumes:
  	- db_data:/var/lib/mysql
	ports:
  	- "3306:3306"

  web:
	build: .
	container_name: webapp
	restart: always
	ports:
  	- "80:80"
	environment:
  	DB_HOST: db
  	DB_USER: webuser
  	DB_PASS: webpass
  	DB_NAME: webapp
	depends_on:
  	- db

volumes:
  db_data:
